core/urls.py
from django.conf.urls import url
from core import views

urlpatterns = [
    url(r'^search/$', views.student_search),
    url(r'^get_students_by_faculty/$', views.get_students_by_faculty),
    url(r'^students/(?P<name>\w+)-(?P<surname>\w+)', views.student_info, name="student-detail"),
    url(r'^$', views.index, name="home"),
    url(r'^get_specialization/$', views.get_specialization),
    url(r'^get_students/$', views.get_students),
    url(r'^add_rev/', views.add_rev),
]

leave_review/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('core.urls', namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import User
from datetime import datetime

from django.db import models
# Create your models here.


class Faculty(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Faculties"

    def __unicode__(self):
        return self.name


class Specialization(models.Model):
    name = models.CharField(max_length=50)
    faculty = models.ForeignKey(Faculty)

    def __unicode__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    year = models.DateField()
    group = models.CharField(max_length=15)
    specialization = models.ForeignKey(Specialization)
    photo = models.ImageField(blank=True, null=True, upload_to='students')

    def get_faculty(self):
        return self.specialization.faculty

    def __unicode__(self):
        return self.name + " " + self.surname


class Review(models.Model):
    review = models.TextField()
    date = models.DateTimeField('date created', default=datetime.now)
    about = models.ForeignKey(Student)
    author = models.ForeignKey(User)

core/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.forms import ModelForm
from .models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('review', )
        widgets = {
            'review': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }

core/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from datetime import datetime

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .models import Student, Faculty, Specialization, Review


def index(request):
    if request.method == 'GET':
        faculties = Faculty.objects.distinct()
        message = request.session.get('message', "")
        students = Student.objects.filter(specialization__faculty__name='Инженерный')
        paginator = Paginator(students, 4)
        students = paginator.page(1)
        context = {'faculties': faculties, 'message': message,
                   'students': students}
        return render(request, 'core/new_index.html', context)


@csrf_protect
def get_specialization(request):
    if request.method == 'GET':
        if request.GET.get('faculty', None) is not None:
            faculty = request.GET['faculty']
            specializations = Specialization.objects.filter(faculty__name=faculty)
            return render(request, 'core/specializations.html',
                          {'specializations': specializations})


def get_students_by_faculty(request):
    if request.method == 'GET':
        faculty = request.GET['faculty']
        students = Student.objects.filter(specialization__faculty__name=faculty)
        paginator = Paginator(students, 4)
        page = int(request.GET.get('page', 1))
        try:
            students = paginator.page(page)
        except PageNotAnInteger or EmptyPage:
            students = paginator.page(1)

        context = {'students': students}
        return render(request, "core/new_subtemplate.html", context)


def get_students(request):
    if request.method == 'GET':
        page = request.GET['page']
        specialization = request.GET.get('specialization', None)
        faculty = request.GET.get('faculty', None)
        context = {'specialization': True}
        print faculty, specialization
        if specialization is not None:
            students = Student.objects.filter(specialization__name=specialization)
        else:
            del context['specialization']
            students = Student.objects.filter(specialization__faculty__name=faculty)
        paginator = Paginator(students, 4)
        try:
            students = paginator.page(int(page))
            print "ok"
        except PageNotAnInteger or EmptyPage:
            students = paginator.page(1)
        context['students'] = students
        return render(request, 'core/new_subtemplate.html', context)


def student_info(request, name, surname):
    if request.method == 'GET':
        student = get_object_or_404(Student, name=name, surname=surname)
        reviews = Review.objects.filter(about__name=name, about__surname=surname).order_by('-date')
        return render(request, 'core/all_reviews.html',
                      {'reviews': reviews, 'name': name, 'surname': surname,
                       'year': student.year.year,
                       'specialization': student.specialization.name,
                       'photo_url': student.photo,
                       })


@login_required
def add_rev(request):
    if request.method == 'GET':
        author = request.user
        about = Student.objects.get(name=request.GET['name'], surname=request.GET['surname'])
        date = datetime.now()
        review = Review(date=date, about=about, author=author, review=request.GET['content'])
        review.save()
        reviews = Review.objects.filter(about__name=about.name, about__surname=about.surname).order_by('-date')
        return render(request, 'core/updated_reviews.html',
                      {'reviews': reviews, })


def student_search(request):
    name = request.GET.get('name', None)
    surname = request.GET.get('surname', None)
    if name == "-1":
        a = Student.objects.filter(specialization__faculty__name='Инженерный')
        students = Paginator(a, 4).page(1)
        return render(request, 'core/new_subtemplate.html',
                      {'students': students})

    if name is None:
        name = ""
    if surname is None:
        surname = ""

    students_list1 = Student.objects.filter(Q(name__startswith=name, surname__startswith=surname)
                                            | Q(name__startswith=surname, surname__startswith=name))
    students = students_list1
    paginator = Paginator(students, 4)
    students = paginator.page(1)
    context = {'students': students}
    return render(request, 'core/new_subtemplate.html', context)

core/templates/core/all_reviews.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Review App</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link href="{% static 'css/materialize.css'%}" rel="stylesheet">
  <link href="{% static 'css/account/styles.css' %}" rel="stylesheet">

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div id="header" class="card">
          <div id="logo"><a id="main-link" href="/">Review App</a></div>
          {% if request.user.is_authenticated %}
            <div id="logout-button-div"><a href="/accounts/logout" class="waves-effect waves-light btn logout-button">Logout</a></div>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col s12">
        <div class="student card" >
          <div class="card name-div"><a class="name" href="{% url 'core:student-detail' name surname %}">{{ student.name}} {{ student.surname }}</a></div>
            <div class="photo"><img src="{{ MEDIA_URL }}/{{ photo_url.url }}" class="responsive-img" width="136px"; height="115px" alt="" /></div>
              <div class="info"> <div class="student-name">Name : {{ name }} </div>
                                 <div class="student-surname">Surname: {{ surname }} </div>
                                 <div class="student-year">Graduation Year: {{ year }} </div>
                                 <div class="student-year">Specialization: {{ specialization }} </div>
              </div>


          </div>
        </div>

        <div class="col s12 all-reviews-container">

        <div class="add-review-container" style="margin-top: 20px !important; margin-bottom: 0 !important">
            <div class="row pis">
              <form class="col s12" method="get">
                  <div class="input-field col s12 card" style="margin-bottom: 0 !important;">
                    <textarea id="textarea1" style="padding: 0.85rem 0" class="materialize-textarea" placeholder="Write your review here..."></textarea>
                  </div>
              </form>
            </div>

            {% if request.user.is_authenticated %}
              <div style="display: inline-block; width: 100%;"><button  class="next waves-effect waves-light btn" onclick='addReview("{{name}}","{{surname}}")' style="margin-top: -10px; float: right;">Add Review</button></div>
            {% else %}
              <a class="next waves-effect waves-light btn add-review-button" href='/accounts/login/?next=/students/{{name}}-{{surname}}' style="font-size: 80% !important; min-width: 100px; width: 23%;">LOGIN TO LEAVE REVIEWS</a>
            {% endif %}

        </div>

          <div class="review">
          <div id="reviews">
            {% if reviews %}
              {% for review in reviews %}
                  <div class="row">
                      <div class="col s12"> 
                        <div class="single-review card"> 
                          <div class="card-content" style="padding-top: 0 !important">
                            <span class="card-title">{{review.author}}</span>
                            <p>{{review.review}}</p>
                          </div>
                          <div class="card-action">
                            {{review.date}}
                          </div>
                      </div>
                    </div>
                  </div>
              {% endfor %}
            {% endif %}
          </div>
          </div>
        </div>
    </div>
  </div>

  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{%  static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/myScript.js' %}"></script>

</body>
</html>

core/templates/core/new_index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>Review App</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link href="{% static 'css/materialize.css'%}" rel="stylesheet">
  <link href="{% static 'css/screen.css' %}" rel="stylesheet">

  </head>
<body>

<div class="container">
  <div class="row">
    <div class="col s12">
        <div id="header" class="card" style="margin: 0 0 0 0 !important;">
          <div id="logo"><a id="main-link" href="/">Review App</a></div>
          {% if request.user.is_authenticated %}
            <div id="logout-button-div"><a href="/accounts/logout" class="waves-effect waves-light btn logout-button">Logout</a></div>
          {% endif %}
        </div>
    </div>
  </div>

    <div class="row">
      <div class="input-field col s12" id="search">
        <div class="card">
          <span  style="display: inline-block; padding: 1px"><img src="{% static 'css/img/search-icon.svg' %}" id="search-img"></img></span>
          <span style='display: inline-block; margin-left:3%; width: 90%;'><input placeholder="Search..." id="name" type="text" class="validate" autocomplete="off" style="margin-left: 10px;"></span>
          <label class="active" for="first_name2"></label>
        </div>
      </div>
    </div>


    <div class="col s12">
      <div class="all-faculties card">
        {% if faculties %}
          {% for faculty in faculties %}
          <div class="faculty" style="display: inline-block !important;">
            <input name="group1" type="radio" id="{{faculty}}" onchange="addSpecializations(this)" />
            <label for="{{faculty}}">{{faculty}}</label>
          </div>
          {% endfor %}
        {% endif %}
      </div>


      <div class="all-specializations card" style="margin-bottom: 10px !important; margin-top: 10px !important;">
        {% if specializations %}
          {% for specialization in specializations %}
          <div class="specialization" style="display: inline-block !important;">
            <input name="group2" type="radio" id="{{specialization}}" onchange="addStudents(this)" />
            <label for="{{specialization}}">{{specialization}}</label>
          </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div id="container" class="box">
              {% if students %}
                {% for student in students %}

                  <div class="student card hoverable" onclick="redirect(this)">
                    <div class="photo" style="margin: 0 !important">
                      <a class="name" href="{% url 'core:student-detail' student.name student.surname %}">
                        <img src="{{ student.photo.url }}" class="responsive-img" width="180px" height="180px" alt="" />
                      </a>
                      </div>
                    <div class="info"> <div class="student-name">Name : {{ student.name }} </div>
                                         <div class="student-surname">Surname: {{ student.surname }} </div>
                                         <div class="student-year">Graduation Year: {{ student.year.year }} </div>
                    </div>
                  </div>

                {% endfor %}
              {% endif %}

              <div class="pagination">
                  <span class="step-links">
                      {% if students and students.has_previous %}
                          {% if specialization %}
                            <a class="prev waves-effect waves-light btn" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>previous</a>
                          {% else %}
                            <a class="prev waves-effect waves-light btn" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}")'>previous</a>
                          {% endif %}
                      {% else %}
                          <a class="prev waves-effect waves-light btn disabled">PREVIOUS</a>
                      {% endif %}


                      {% if students and students.has_next %}
                        {% if specialization %}
                          <a class="next waves-effect waves-light btn" href="" onclick='Retrieve(event,{{ students.next_page_number }}, "{{ students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>next</a>
                        {% else %}
                          <a class="next waves-effect waves-light btn" href="" onclick='Retrieve(event,{{ students.next_page_number}}, "{{students.0.specialization.faculty.name }}")'>next</a>
                        {% endif %}
                      {% else %}
                        <a class="next waves-effect waves-light btn disabled">NEXT</a>
                      {% endif %}
                  </span>
              </div>
          </div>
    </div>

  </div>
</div>

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{%  static 'js/materialize.js' %}"></script>
<script src="{% static 'js/myScript.js' %}"></script>
</body>
</html>

core/templates/core/new_subtemplate.html
{% load staticfiles %}
{% if students %}
  {% for student in students %}
  <div class="student card hoverable" onclick="redirect(this)">
    <div class="photo">
      <a class="name" href="{% url 'core:student-detail' student.name student.surname %}">
        <img src="{{ student.photo.url }}" class="responsive-img" width="180px" height="180px" alt="" />
      </a>
      </div>
    <div class="info"> <div class="student-name">Name : {{ student.name }} </div>
                         <div class="student-surname">Surname: {{ student.surname }} </div>
                         <div class="student-year">Graduation Year: {{ student.year.year }} </div>
    </div>
  </div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if students and students.has_previous %}
            {% if specialization %}
              <a class="prev waves-effect waves-light btn" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>previous</a>
            {% else %}  
              <a class="prev waves-effect waves-light btn" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}")'>previous</a>
            {% endif %}
        {% else %}
            <a class="prev waves-effect waves-light btn disabled">PREVIOUS</a>
        {% endif %}


        {% if students and students.has_next %}
          {% if specialization %}
            <a class="next waves-effect waves-light btn" href="" onclick='Retrieve(event,{{ students.next_page_number }}, "{{ students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>next</a>
          {% else %}
            <a class="next waves-effect waves-light btn" href="" onclick='Retrieve(event,{{ students.next_page_number}}, "{{students.0.specialization.faculty.name }}")'>next</a>
          {% endif %}
        {% else %}
          <a class="next waves-effect waves-light btn disabled">NEXT</a>
        {% endif %}
    </span>
</div>
    
{% endif %}

core/templates/core/specializations.html
{% if specializations %}
  {% for specialization in specializations %}
  <div class="specialization" style="display: inline-block; padding: 10px">
    <input name="group2" type="radio" id="{{specialization}}" onchange="addStudents(this)" />
    <label for="{{specialization}}">{{specialization}}</label>
  </div>
  {% endfor %}
{% endif %}

core/templates/core/students.html
<ul id="students-list" class="list-group">
  {% if students %}
    {% for student in students %}
      <div id="student-filtered-results">
        <a href="{% url 'core:student-detail' student.name student.surname %}">
          <img id="student-photo" src="{{ student.photo.url }}" width="80" height="80">
        </a>
        <div id="main-info">
          Name: {{student.name}} <br>
          Surname: {{ student.surname }} <br>
          Graduation Year: {{ student.year.year }}
        </div>
      </div>
    {% endfor %}
  {% endif %}
</ul>
<div class="pagination">
    <span class="step-links">
        {% if students and students.has_previous %}
            {% if specialization %}
              <a id="prev" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>previous</a>
            {% else %}
              <a id="prev" href="" onclick='Retrieve(event,{{students.previous_page_number}}, "{{students.0.specialization.faculty.name }}")'>previous</a>
            {% endif %}
        {% endif %}

        {% if students %}
        <span class="current">
            Page {{ students.number }} of {{ students.paginator.num_pages }}.
        </span>
        {% endif %}

        {% if students and students.has_next %}
          {% if specialization %}
            <a id="next" href="" onclick='Retrieve(event,{{ students.next_page_number }}, "{{ students.0.specialization.faculty.name }}", "{{ students.0.specialization.name }}")'>next</a>
          {% else %}
            <a id="prev" href="" onclick='Retrieve(event,{{students.next_page_number}}, "{{students.0.specialization.faculty.name }}")'>next</a>
          {% endif %}
        {% endif %}
    </span>
</div>

core/templates/core/subtemplate.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/subtemplate.css'%}">
<ul id="students-list" class="list-group">
  {% if students %}
    {% for student in students %}
      <div id="student-filtered-results">
        <a href="http://{{host}}/students/{{ student.name }}-{{ student.surname }}/">
          <img id="student-photo" src="{{ student.photo.url }}" width="80" height="80">
        </a>
        <div id="main-info">
          Name: {{student.name}} <br>
          Surname: {{ student.surname }} <br>
          Graduation Year: {{ student.year.year }}
        </div>
      </div>
    {% endfor %}
  
</ul>


<div class="pagination">
    <span class="step-links">
        {% if students.has_previous %}
            <a id="prev" href="" onclick="prev(event)">previous</a>
        {% endif %}

        {% if students %}
        <span class="current">
            Page {{ students.number }} of {{ students.paginator.num_pages }}.
        </span>
        {% endif %}

        {% if students.has_next %}
            <a id="next" href="" onclick="next(event)">next</a>
        {% endif %}
    </span>
</div>
{% endif %}

core/templates/core/updated_reviews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="review">
          <div id="reviews">
            {% if reviews %}
              {% for review in reviews %}
                  <div class="row">
                      <div class="col s12">
                        <div class="single-review card">
                          <div class="card-content" style="padding-top: 0 !important">
                            <span class="card-title">{{review.author}}</span>
                            <p>{{review.review}}</p>
                          </div>
                          <div class="card-action">
                            {{review.date}}
                          </div>
                      </div>
                    </div>
                  </div>
              {% endfor %}
            {% endif %}
          </div>
    </div>
</body>
</html>